base: ".."
cache: "{locations.base}/cache"
resources: "{locations.base}/resources"
views: "{locations.resources}/templates"
routes: "{locations.resources}/routes"
models: "{locations.base}/menu_models"
model_resources: "{locations.models}/resources"
migrations: "{locations.model_resources}/migrations"
