base: ".."
cache: "{locations.base}/cache"
resources: "{locations.base}/resources"
views: "{locations.resources}/templates"
routes: "{locations.resources}/routes"
models:
  base: "{locations.base}/menu_models"
  resources: "{locations.models.base}/resources"
  migrations: "{locations.models.resources}/migrations"
