base: "realpath(dirname($_SERVER['SCRIPT_FILENAME']) . '/..')"
cache: "{locations.base}/cache"
resources: "{locations.base}/resources"
views: "{locations.resources}/templates"
routes: "{locations.resources}/routes"
models:
  base: "{locations.base}/menu_models"
  resources: "{locations.models.base}/resources"
  migrations: "{locations.models.resources}/migrations"
configs:
  base: "{locations.base}/modules/Config"
  resources: "{locations.configs.base}/resources"
  migrations: "{locations.configs.resources}/migrations"
